import Head from "next/head";
import TopSection from "../components/TopSection";
import ServiceSection from "../components/ServiceSection";
import DownloadSection from "../components/DownloadSection";
import ContactSection from "../components/ContactSection";
import AboutSection from "../components/AboutSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>FooDo.. Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./Assets/logo.png" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"
        />
      </Head>
      <main >
        <div className="border border-danger">
        <TopSection  />
        </div>
        <div className="border border-danger">
        <ServiceSection  />

        </div>
        <div className="border border-danger">
        <DownloadSection />

        </div>
        <div className="border border-danger">
        <AboutSection />

        </div>
        <div className="border border-danger">
        <ContactSection />

        </div>
      </main>

      <footer className="footer">
      <h5>Foodo &copy; Uday</h5>
        <script
          src="https://unpkg.com/react/umd/react.production.min.js"
          crossorigin
        ></script>

        <script
          src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"
          crossorigin
        ></script>

        <script
          src="https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js"
          crossorigin
        ></script>
      </footer>
    </div>
  );
}
